### ISSUE TITLE
ghcr.io require token access (apps token or pats)

### ISSUE THREAD

**Issue by poblin-orange** [orange-cloudfoundry/paas-templates#1172] opened 2021-04-24 12:22 UTC
### Expected behavior

* As a paas-templates operator
* In order to
  * have correct k8s-jcr => ghcr.io docker image proxy
* I need 
  * to setup authentication token to avoid github rate limiting

### Observed behavior

jcr-k8s logs:
```
│ :repository:teliaoss/github-pr-resource:pull'                                                                                                              │
│ artifactory 2021-04-24T12:22:14.471Z [jfrt ] [ERROR] [57e981ee9deea3c1] [.DockerV2RemoteRepoHandler:329] [ttp-nio-8081-exec-12] - Unable to fetch tags for │
│  'teliaoss/github-pr-resource': 'java.lang.IllegalStateException: Can't fetch token for repo: ghcr-io realm: https://ghcr.io/token scope:repository:teliao │

```

### Solution outline
- use github PAT (personal access token) for jcr-k8s remote config see https://www.jfrog.com/jira/si/jira.issueviews:issue-html/RTFACT-23546/RTFACT-23546.html

### Affected releases

* 51.0.0
* earlier versions

**Comment by JCL38-ORANGE** [comment] 2021-05-07 09:19
Maybe the root cause of https://github.com/orange-cloudfoundry/paas-templates/issues/1136

**Comment by poblin-orange** [comment] 2021-05-07 09:20
if new token required, align current github token usage (shared/secrets.yml + credhub seeding)

**Comment by o-orand** [comment] 2021-08-13 07:27
I don't think we still encounter this issue.

**Comment by gberche-orange** [comment] 2021-09-03 09:31
closing, reopen if it reproduces

**Comment by JCL38-ORANGE** [comment] 2021-11-05 09:09
Seems to appear again in BRMC PPROD/PROD : 
artifactory 2021-11-05T09:05:43.595Z [jfrt ] [WARN ] [1419844d3f6f78dd] [o.a.r.RemoteRepoBase:505      ] [ttp-nio-8081-exec-96] - ghcr-io: Error in getting information for 'cftoolsmiths/cron-resource/ │
│ artifactory 2021-11-05T09:05:46.238Z [jfrt ] [WARN ] [8784d6558d631bbb] [o.a.r.RemoteRepoBase:505      ] [http-nio-8081-exec-8] - registry.gitlab.com: Error in getting information for 'cftoolsmiths/cr │
│ artifactory 2021-11-05T09:05:46.559Z [jfrt ] [WARN ] [8784d6558d631bbb] [o.a.r.RemoteRepoBase:505      ] [http-nio-8081-exec-8] - ghcr-io: Error in getting information for 'cftoolsmiths/cron-resource/ │
│ artifactory 2021-11-05T09:06:36.010Z [jfrt ] [WARN ] [41ce7b7b789e9b27] [o.a.r.RemoteRepoBase:505      ] [ttp-nio-8081-exec-96] - registry.gitlab.com: Error in getting information for 'olhtbr/metadata │
│ artifactory 2021-11-05T09:06:36.324Z [jfrt ] [WARN ] [41ce7b7b789e9b27] [o.a.r.RemoteRepoBase:505      ] [ttp-nio-8081-exec-96] - ghcr-io: Error in getting information for 'olhtbr/metadata-resource/2. │
│ artifactory 2021-11-05T09:06:36.339Z [jfrt ] [WARN ] [344bb3131af03e04] [o.a.r.RemoteRepoBase:505      ] [ttp-nio-8081-exec-43] - registry.gitlab.com: Error in getting information for 'olhtbr/metadata │
│ artifactory 2021-11-05T09:06:37.143Z [jfrt ] [WARN ] [d85babfbd3540a68] [o.a.r.RemoteRepoBase:505      ] [ttp-nio-8081-exec-49] - registry.gitlab.com: Error in getting information for 'olhtbr/metadata │
│ artifactory 2021-11-05T09:06:37.146Z [jfrt ] [WARN ] [5e5c27b863ffe31f] [o.a.r.RemoteRepoBase:505      ] [ttp-nio-8081-exec-79] - registry.gitlab.com: Error in getting information for 'olhtbr/metadata │
│ artifactory 2021-11-05T09:06:37.481Z [jfrt ] [WARN ] [d85babfbd3540a68] [o.a.r.RemoteRepoBase:505      ] [ttp-nio-8081-exec-49] - ghcr-io: Error in getting information for 'olhtbr/metadata-resource/sh │
│ artifactory 2021-11-05T09:06:37.483Z [jfrt ] [WARN ] [5e5c27b863ffe31f] [o.a.r.RemoteRepoBase:505      ] [ttp-nio-8081-exec-79] - ghcr-io: Error in getting information for 'olhtbr/metadata-resource/2. │
│ artifactory 2021-11-05T09:06:37.639Z [jfrt ] [WARN ] [358d1aa72e290c8e] [o.a.r.RemoteRepoBase:505      ] [tp-nio-8081-exec-120] - registry.gitlab.com: Error in getting information for 'olhtbr/metadata │
│ artifactory 2021-11-05T09:06:37.962Z [jfrt ] [WARN ] [358d1aa72e290c8e] [o.a.r.RemoteRepoBase:505      ] [tp-nio-8081-exec-120] - ghcr-io: Error in getting information for 'olhtbr/metadata-resource/2. │
│ artifactory 2021-11-05T09:06:38.164Z [jfrt ] [WARN ] [5218b76ef581aa31] [o.a.r.RemoteRepoBase:505      ] [tp-nio-8081-exec-108] - registry.gitlab.com: Error in getting information for 'olhtbr/metadata │
│ artifactory 2021-11-05T09:06:38.485Z [jfrt ] [WARN ] [5218b76ef581aa31] [o.a.r.RemoteRepoBase:505      ] [tp-nio-8081-exec-108] - ghcr-io: Error in getting information for 'olhtbr/metadata-resource/sh │
│ artifactory 2021-11-05T09:06:38.864Z [jfrt ] [WARN ] [933cd3edf0ca0b0f] [o.a.r.RemoteRepoBase:505      ] [ttp-nio-8081-exec-15] - registry.gitlab.com: Error in getting information for 'olhtbr/metadata │
│ artifactory 2021-11-05T09:06:39.182Z [jfrt ] [WARN ] [933cd3edf0ca0b0f] [o.a.r.RemoteRepoBase:505      ] [ttp-nio-8081-exec-15] - ghcr-io: Error in getting information for 'olhtbr/metadata-resource/sh │
ckerV2RemoteRepoHandler:329] [ttp-nio-8081-exec-15] - Unable to fetch tags for 'cftoolsmiths/cron-resource': 'java.lang.IllegalStateException: Can't fetch token for repo: registry.gitlab.com realm: ht │
│ ckerV2RemoteRepoHandler:329] [ttp-nio-8081-exec-15] - Unable to fetch tags for 'cftoolsmiths/cron-resource': 'java.lang.IllegalStateException: Can't fetch token for repo: ghcr-io realm: https://ghcr.i │
│

**Comment by o-orand** [comment] 2021-11-09 08:24
@JCL38-ORANGE , these errors are expected as requested images exists only on DockerHub. It seems related to #1394. 
I think we can re-close this issue.

**Closed** 2022-01-10 10:49 UTC
Labels: bug, kb, not reproduced
