### ISSUE TITLE
optimize PaaS Template install between services and stemcells

### ISSUE THREAD

**Issue by regismarg** [orange-cloudfoundry/paas-templates#402] opened 2019-05-21 13:21 UTC
### Expected behavior
As an ops team, i try to optimze the version installation global time
to be able to cut the installation between different parts en short, i would like to have a process to separate the works related to services installation and stemcell upgrades

**Comment by regismarg** [comment] 2019-05-21 13:24
Proposition to optimize time:
During a deployment, when a director is used:
vérify before if the stemcells and releases ares available 
If not, :  execute automatically the  team upload jobs.

**Comment by poblin-orange** [comment] 2019-06-08 11:54
related to https://github.com/orange-cloudfoundry/cf-ops-automation/issues/264

**Comment by gberche-orange** [comment] 2020-03-12 15:51
possibly solved/duplicate of #44

**Closed** 2020-04-03 12:36 UTC
Labels: discuss, enhancement, upstream bug
