### ISSUE TITLE
Logsearch-ops ES exporter : The prometheus-exporter is not able to reach the logsearch-ops master

### ISSUE THREAD

**Issue by wdesplas** [orange-cloudfoundry/paas-templates#642] opened 2019-12-12 09:41 UTC
### Expected behavior
The logsearch-ops master must have his own exporter using the prometheus-bosh release for elasticsearch i.e : https://github.com/justwatchcom/elasticsearch_exporter instead of having a stating entry in the DNS recursor.
### Observed behavior
The logsearch-ops is deployment using dynamic IP. In fact, in the integration platform, we have these following IP:
```
elasticsearch_master/060f8cde-7936-49ac-a61f-e4a668d7d380   running        z1  192.168.99.113  logsearch-ops  
elasticsearch_master/d711bf72-7d10-465a-9d0b-43065b14731c   running        z1  192.168.99.112  logsearch-ops  
elasticsearch_master/eadb876b-457b-4156-bffb-102e3887a702   running        z2  192.168.99.114  logsearch-ops
```
and on our production platform we have:
```
elasticsearch_master/0de7f55c-7e91-4325-b42a-6df8abe73859   running        z1  192.168.99.97  
elasticsearch_master/1a9cbc82-a65b-45b9-8ddd-9d5b871b5922   running        z2  192.168.99.98  
elasticsearch_master/f28f0e2d-a022-48c7-9170-b11d19c06d88   running        z1  192.168.99.96
```
These IP are diffents from the integration platform and the production as they are automatically assign.
However, on DNS recursor, the IP is statically define in paas-templates/micro-depls/dns-recursor/template/1-dns-aliases-operators.yml
```
- type: replace
  path: /instance_groups/name=dns-recursor/jobs/name=bosh-dns/properties/aliases/es-master-ops.internal.paas?
  value: [192.168.99.26]
```
As consequence, the prometheus-exporter-master fired an alarm as it is not possible for the elasticsearch_exporter jobs to find out the dns entry es-master-ops.internal.paas. 

### Workaround
As workaround, I have override the entry in /etc/hosts manually.

### Analysis and solution outline
A solution is  dropping the elasticsearch_exporter in prometheus-exporter-master deployment and add the exporter in the logsearch-ops deployment using consume properties.

**Comment by poblin-orange** [comment] 2019-12-12 10:40
looks like a duplicate of https://github.com/orange-cloudfoundry/paas-templates/issues/576

**Closed** 2020-03-17 15:10 UTC
Labels: bug, duplicate
