### ISSUE TITLE
COAB rabbitmq MVP

### ISSUE THREAD

**Issue by gberche-orange** [orange-cloudfoundry/paas-templates#467] opened 2019-06-28 15:14 UTC
### Expected behavior

As a platform user, I need a rabbitmq service not suffering from noisy neighbors effects, in order to operate applications that heavily rely on rabbitmq

### Observed behavior

Only shared rabbitmq cluster is offered

### Affected release

Reproduced on version 41.x

**Comment by poblin-orange** [comment] 2019-06-28 19:44
duplicate of #168

**Closed by poblin-orange** 2019-06-28 19:44 UTC
Labels: enhancement, feature
