### ISSUE TITLE
enable mariadb connector-J HA feature

### ISSUE THREAD

**Issue by poblin-orange** [orange-cloudfoundry/paas-templates#730] opened 2020-03-19 15:41 UTC
### Expected behavior
As a platform runner, offering cf-mysql service, i need to ensure the offered service is HA 

### related to :
- #676 

### Observed behavior
A single proxy switchbard ip is provided in VCAP_SERVICES.

### references
Mariadb connect J 1.2 adds support for multi-master (galera)

- https://mariadb.com/kb/en/failover-and-high-availability-with-mariadb-connector-j/
- https://mariadb.com/kb/en/about-mariadb-connector-j/#failover-and-load-balancing-modes
- https://mariadb.com/kb/en/mariadb-connector-j-130-release-notes/#sequential-failover-parameter

- java buildpack support Maria DB jdbc 2.5.4 https://github.com/cloudfoundry/java-buildpack/releases/tag/v4.28

### study
- [x] check mariab version installed by cloudfoundry java buildpack
- [ ] sample app leveraging 2 ips in cups
- [ ] service broker configuration update / evolution to provide the 2 switch proxy ip in VCAP SERVICES jdbc url, with sequential policy. Give the HA url as a separate entry in VCAP_SERVICES

**Comment by gberche-orange** [comment] 2022-03-14 15:04
duplicate of https://github.com/orange-cloudfoundry/paas-templates/issues/921

**Closed** 2022-03-18 09:54 UTC
Labels: enhancement, discuss
