### ISSUE TITLE
 alert emails are no longer sent

### ISSUE THREAD

**Issue by CDallosto-orange** [orange-cloudfoundry/paas-templates#962] opened 2020-10-13 13:00 UTC
### Expected behavior

* As a paas-templates operator
* In order to operate platform
* I need to send alert emails through the FED

### Observed behavior
no more mail since about 47.0.3 upgrade
### Affected releases

47.0.3

**Comment by poblin-orange** [comment] 2020-10-16 07:27
issue solved by restarting haproxy job. Root cause is unclear (dns resolution expiration might be broken in our haproxy configuration, resulting in unability to switch to the new mail backend following a GTM switch ...). Keeping the issue opened

**Comment by poblin-orange** [comment] 2020-10-16 10:05
seems the GTM is configures as round robin DNS, and we observe alternate dns resolution on the haproxy as expected. Closing

**Comment by JCL38-ORANGE** [comment] 2020-11-10 15:47
Always present with v49.0.0.
Workaround applied with success : 
bosh ssh to-intranet
sudo -i
monit stop haproxy
monit start haproxy

**Comment by poblin-orange** [comment] 2020-11-20 09:43
TODO @poblin-orange :
- [ ] - open issue on haproxy
- [ ] - propose pull request

**Closed** 2020-11-20 13:56 UTC
Labels: bug, kb, upstream bug
