### ISSUE TITLE
Ssh-Envoy CIDR conflict

### ISSUE THREAD

**Issue by JSimon-Orange** [orange-cloudfoundry/paas-templates#571] opened 2019-10-13 17:35 UTC
### Expected behavior
When using a docker based component that need an tcp intranet-interco, ssh-envoy should route to the intranet

### Observed behavior
Component based on docker use the same CIDR as ssh-envoy. It result has a wrong routing that cannot get to the intranet

### Affected release
v41.0.0
v42.0.0

**Comment by poblin-orange** [comment] 2019-10-14 08:46
With v43, we should have a no more 172.x routes set from the marketplace (intranet access only).
This config wont be needed anymore ?

**Comment by JSimon-Orange** [comment] 2019-10-14 09:09
We may have a try on v43 with disabling locally this branch and see for v44

**Comment by gberche-orange** [comment] 2019-10-15 07:19
@JSimon-Orange can you please confirm this issue is a duplicate of #528 ?

**Comment by JSimon-Orange** [comment] 2019-10-15 07:53
My bad, your right @gberche-orange. We can close this one.

**Closed** 2019-10-15 16:14 UTC
Labels: discuss, enhancement, ofr contrib
