### ISSUE TITLE
broker (osb) monitoring

### ISSUE THREAD

**Issue by gcordierOrange** [orange-cloudfoundry/paas-templates#927] opened 2020-10-05 09:04 UTC
### Expected behavior

* As a paas-templates operator 
* In order to monitor broker activity, quota usage
* I need to have an alert when create service is ko for the client

### Observed behavior
We don't have alert on broker error
For example, i want monitor log to have ERROR in alertmanager

### Affected releases

* 47.0.3
* earlier versions

**Comment by poblin-orange** [comment] 2020-10-05 15:21
@gcordierOrange to clarify. You need alerting when osb broker is down, or you need metrics on service creation/bind per hour/day on which to build alerting ?

**Comment by gcordierOrange** [comment] 2020-10-05 15:28
> @gcordierOrange to clarify. You need alerting when osb broker is down, or you need metrics on service creation/bind per hour/day on which to build alerting ?

I need to know when a creation/bind service fail before the mail of the client.
My use case : 
* A client attend to create a service
* The creation fail because of broker error behind osb
* I want to generate an alert to the operator
Maybe a alert on ELK log

**Comment by gberche-orange** [comment] 2020-10-07 07:27
@gcordierOrange @poblin-orange suspecting this issue is a duplicate of #225, can you please confirm and close #927 as #225 has more context

**Comment by poblin-orange** [comment] 2020-12-04 10:22
duplicate https://github.com/orange-cloudfoundry/paas-templates/issues/225

**Closed by poblin-orange** 2020-12-04 10:22 UTC
Labels: enhancement, feature, marketplace
