### ISSUE TITLE
Console Admin UI should either be fixed either removed from PT

### ISSUE THREAD

**Issue by aurelienbouleau** [orange-cloudfoundry/paas-templates#453] opened 2019-06-19 09:23 UTC
### Expected behavior
As an user of Paas-Templates, I expected that the provided console by default is working properly. 

### Observed behavior
Both console admin UI and Stratos Console are provided but by default customer are directed to Console Admin which is regurlaly having issues. Customers complain about the fact that it remains unclear why The default console is not working properly. 
Is this possible to:
- either remove the Console Admin from PT and switch Stratos to the default link
- Fix the Console Admin ? 
 
### Affected release

Reproduced on version v40

**Comment by poblin-orange** [comment] 2019-06-25 20:31
duplicate of #251  ?

**Comment by T0FFF** [comment] 2019-07-17 08:24
The service has been disabled.

**Closed by T0FFF** 2019-07-17 08:24 UTC
Labels: duplicate
