### ISSUE TITLE
[Bootstrap] Step 10: Deploy master-depls jobs manually with Concourse - bosh openstack cpi upload not present

### ISSUE THREAD

**Issue by wdesplas** [orange-cloudfoundry/paas-templates#156] opened 2018-10-10 09:36 UTC
**Affected Release**
v35.0.1

**Trace**
Task 362 | 08:08:20 | Preparing deployment: Preparing deployment (00:00:00)
                    L Error: Release 'bosh-openstack-cpi' doesn't exist
Task 362 | 08:08:20 | Error: Release 'bosh-openstack-cpi' doesn't exist

**Workaround:**
bosh upload-release --sha1 34d07e203a4442c81a2f2391262fbadf5bc6eaea \
  https://bosh.io/d/github.com/cloudfoundry/bosh-openstack-cpi-release?v=39

**Explaination**
During the bosh-master deployment phase, we have an error due to abscence of the bosh openstack CPI release . 
The upload is present in the deployment-dependencies-openstack configuration file but not force in the openstack-cpi-operators.
We have upload the release manually as workaround.

**Comment by poblin-orange** [comment] 2018-10-16 16:15
duplicate of #160, root cause is COA regression.

**Closed by poblin-orange** 2018-10-16 16:15 UTC
Labels: duplicate
