### ISSUE TITLE
traefik desactivate gzip compression

### ISSUE THREAD

**Issue by obeyler** [orange-cloudfoundry/paas-templates#590] opened 2019-11-04 09:50 UTC
### Expected behavior
traefik ingress controller has trouble with gzip compression on content-type text/event-stream (these kind of content-type is used by concourse to display job result)
as workaround I desactivated gzip compression
=> traefik team has create a way to desactivate gzip compression
https://github.com/containous/traefik/pull/5721
but the chart doesn't implement it yet
### Affected release
v44

**Comment by poblin-orange** [comment] 2019-11-08 10:02
v44 sets a workaround configuration (disable gzip).
Waiting for upstream fixes

**Comment by obeyler** [comment] 2020-03-17 14:45
need to be confirm with last traefik V2 currently used

**Comment by poblin-orange** [comment] 2021-03-24 17:33
cant reproduce with concourse + traefik helm as of v51. closing

**Closed by poblin-orange** 2021-03-24 17:33 UTC
Labels: bug, k8s, upstream bug
