### ISSUE TITLE
multi-region dedicated rabbitmq

### ISSUE THREAD

**Issue by poblin-orange** [orange-cloudfoundry/paas-templates#1038] opened 2020-12-16 09:14 UTC
### Expected behavior

* As a marketplace user
* In order to 
  * support HA rabbitmq in the marketplace
* I need 
  * a new extended rabbitmq service 

### Affected releases

* x.y
* earlier versions

**Comment by JCL38-ORANGE** [comment] 2021-02-26 08:41
closed because duplicate of https://github.com/orange-cloudfoundry/paas-templates/issues/1088

**Closed by JCL38-ORANGE** 2021-02-26 08:41 UTC
Labels: coab, discuss, enhancement, ha, marketplace
