### ISSUE TITLE
shield monitoring

### ISSUE THREAD

**Issue by gcordierOrange** [orange-cloudfoundry/paas-templates#981] opened 2020-10-26 12:36 UTC
### Expected behavior

* As a paas-templates operator | marketplace user | paas-templates author | paas-templates maintainer
* In order to monitor the status of my backup
* I need to have information about shield backup for my service

### Observed behavior
No centralized informations about backup
 
### Affected releases

* 47
* earlier versions

**Comment by gcordierOrange** [comment] 2020-10-26 12:43
My idea was to simulate the shield exporter : 

1. Each shield generate a file with the sale content that the "shield status" command. This file is generated by a cron job
2. The file have a prometheus format whith some other lobl loke bosh_deployment to link with the deployment.
3. The file is name .prom into de textfile node_exporter directory, so it will be pared by the node exporter
4. Each scrape node_exporter will get the shield status

We need to update de shield deployment to add the cron job who do the extract / transformation.

**Comment by gberche-orange** [comment] 2020-10-28 10:09
thanks @gcordierOrange great idea. Seems a duplicate of https://github.com/orange-cloudfoundry/paas-templates/issues/737#issuecomment-715163529, do you confirm ?

**Comment by gcordierOrange** [comment] 2020-10-28 14:33
> thanks @gcordierOrange great idea. Seems a duplicate of [#737 (comment)](https://github.com/orange-cloudfoundry/paas-templates/issues/737#issuecomment-715163529), do you confirm ?

Yes, the idea is the same, but i think mine idea is more simple for integrate into the existing prometheus.
(great minds think alike)

**Closed** 2020-11-06 09:19 UTC
Labels: marketplace, ofr contrib
