### ISSUE TITLE
Routing rules may disapear upon VM (with 2nd NIC) on re-creation

### ISSUE THREAD

**Issue by JSimon-Orange** [orange-cloudfoundry/paas-templates#704] opened 2020-02-24 14:56 UTC
### Expected behavior
As a platform operator, i want VM with 2 network interfaces have correct and stable table routing on their re-creation.

### Observed behavior
On certain VM (OPS relay, OSB relay, etc ...) we can observe that, in certain case, routing table are not defined correctly.

On instances with double nic operators, we found both interface and gateway are specified in the static routing rule

https://github.com/orange-cloudfoundry/paas-templates/blob/76da8377eb56b283bb3c7b938489cac495facd73/master-depls/intranet-interco-relay/template/vsphere/2-double-nic-ops-operators.yml#L18-L26

However, the interface are not deterministically affected (i.e eth0 and eth1 seem assigned to different networks). When theur do not correspond (gateway and interface) Bosh can not create the new route but does not trace or log it (or i do not see it).

We should not specify the `interface`, the `gateway` property is sufficient

### Affected release
44.0.5

Reproduced on version x.y
45.0.3

### Traces and logs
No traces, no error. Only that : 

```
osb-relay/xxx:/var/vcap/sys/log/routes# cat routes.err.log
SIOCADDRT: Network is unreachable
SIOCDELRT: No such process
SIOCADDRT: File exists
```

**Comment by gberche-orange** [comment] 2020-02-24 15:17
Seems the networking release silently ignores the failed execution of the `route` command:

https://github.com/cloudfoundry/networking-release/blob/ad3930498cd4818fffa225eb13d497c879c222a7/jobs/routes/templates/bin/routes_ctl.erb#L13-L22

The root cause of lack of determinism in NIC interface number allocation is yet to be determined:
- which order is used ? order of networks in the bosh manifest ? No apparent traces of manifest order change as recorded into `master-depls/osb-routing/osb-routing.yml`
- which component is assigning the interface ? Bosh agent ? Bosh director ?

**Comment by poblin-orange** [comment] 2020-02-25 07:51
is the context a bosh recreate (or hm resurrection) or a vmotion move as suggested in #701 ?

I think the expected ethx assignement is manifest order.
However the concrete network configuration is done by bosh-agent. (for disks, director gives some metadata to help bosh-agent correctly assign  /dev/vdx to volumes, should check if NIC "physical" metadata is provided to bosh-agent)

**Comment by JSimon-Orange** [comment] 2020-02-25 10:38
>is the context a bosh recreate (or hm resurrection) or a vmotion move as suggested in #701 ?

No clue on what happen. Looking at bosh tasks history and it does not seem that health manager has seen the VM dead or hanging. No trace of recreate two. The route has just disapear like magic. 

We suspect that NIC has changed while moving manually the VM from an ESX to another.
When we were trying to bosh recreate the VM, the route was not implemented too. 
As i have already experimented, the interface specified in routing rule in the manifest was not corresponding to the actual nic of the VM attributed after the recreate (but it was before the IaaS incident).

**Comment by poblin-orange** [comment] 2020-02-29 00:49
slack thread wrt to ethx assignement order https://cloudfoundry.slack.com/archives/C02HPPYQ2/p1582880544046600?thread_ts=1582878392.045500&cid=C02HPPYQ2

**Comment by poblin-orange** [comment] 2020-03-17 15:14
@JSimon-Orange would you propose a PR removing all references to ethx in static routing ?

**Comment by JSimon-Orange** [comment] 2020-03-17 15:21
Hello @poblin-orange, already done.
This is the 669 ( feature-hotfix-missing-route  )

**Comment by poblin-orange** [comment] 2020-03-18 17:02
Thks @JSimon-Orange 
merged for v46

**Closed by poblin-orange** 2020-03-18 17:02 UTC
Labels: bug, ofr contrib
