### ISSUE TITLE
Shield Jobs Paused on COAB

### ISSUE THREAD

**Issue by jvizier** [orange-cloudfoundry/paas-templates#627] opened 2019-11-20 10:53 UTC
### Expected behavior

Shield jobs on COAB must be unpaused

### Observed behavior

After deployments jobs are paused

c_17365a30-219c-4bb2-b5e1-17f530165b2e  (https://shield-webui-c_17365a30-219c-4bb2-b5e1-17f530165b2e.xxx)  OK
SHIELD sandbox
logged in successfully
* 8e3cfeb4-4121-4d35-8e84-5d7403c3bbb3
* b68368e2-bf18-471a-a56f-c89138581586
* 9b074143-878e-4f35-983d-0e57551109f8
* dc067508-a910-4d6e-8b6c-1b8744e216df

m_42d98098-f967-4d81-b3bf-2779e835ae3c  (https://shield-webui-m_42d98098-f967-4d81-b3bf-2779e835ae3c.xxx)  OK
SHIELD sandbox
logged in successfully
* 8a2e8052-5155-412b-b150-912b9d3ea2a6
* 7a6acc90-124f-4bb9-808d-856351663229
* 13364e27-0c61-4995-8670-6331b3ee7119

m_99799440-4c49-46f7-a1bb-bfbf67cac9bd  (https://shield-webui-m_99799440-4c49-46f7-a1bb-bfbf67cac9bd.xxx)  OK
SHIELD sandbox
logged in successfully
* 9261897c-a85a-437b-bbad-305dfdfe9f43
* dd1722ea-1f7c-4e1f-a294-dc14913d2eb7
* 0f1d026f-2d78-44ce-bff4-ddece3eabd35

m_9eb6f4fb-9a7e-4efe-9dfe-095642a21e47  (https://shield-webui-m_9eb6f4fb-9a7e-4efe-9dfe-095642a21e47.xxx)  OK
SHIELD sandbox
logged in successfully
* d26a99cb-4743-48a5-a350-37febfbe955b
* 31056647-5360-48d7-a654-ad1f79f0495e
* 856d60c7-3d20-4c1d-a1c6-2094ca5bd33b

m_c7565451-9c96-45bf-875b-0a8caf537e2e  (https://shield-webui-m_c7565451-9c96-45bf-875b-0a8caf537e2e.xxx)  OK
SHIELD sandbox
logged in successfully
* 8fc91b9d-41ce-4174-bdc4-55aba6d81dd1
* 318085a3-f7d7-49e3-8ff6-5a29f2d0e032
* 183ded58-1fcc-4e6e-beb0-dc5ab3f4c595

y_1e5d39c0-c5b4-4e58-b0b3-54693da13e6b  (https://shield-webui-y_1e5d39c0-c5b4-4e58-b0b3-54693da13e6b.xxx)  OK
SHIELD sandbox
logged in successfully
* 8aaad3e7-c43a-4768-9bc1-c821d2f5d653 

y_203eeaa1-dec6-4ea2-85ba-7685e0339180  (https://shield-webui-y_203eeaa1-dec6-4ea2-85ba-7685e0339180.xxx)  OK
SHIELD sandbox
logged in successfully
* f676fea3-bdd8-45f6-ad54-800401007aae 

y_da888d03-436a-462e-9cdd-98c42dfb6257  (https://shield-webui-y_da888d03-436a-462e-9cdd-98c42dfb6257.xxx)  OK
SHIELD sandbox
logged in successfully
* 73ca3d31-5c7d-447e-8b82-5f523793922c

### Affected release

Reproduced on version 42.01

**Comment by JCL38-ORANGE** [comment] 2019-11-20 12:09
duplicate of https://github.com/orange-cloudfoundry/paas-templates/issues/597

**Closed** 2019-11-21 18:29 UTC
Labels: bug, duplicate
