### ISSUE TITLE
CF update V40 job cloud_controller_ng failed

### ISSUE THREAD

**Issue by obeyler** [orange-cloudfoundry/paas-templates#359] opened 2019-05-02 18:46 UTC
### Expected behavior
all job should be started

### Observed behavior
job cloud_controller_ng failed
Task 1238327 | 17:57:16 | Updating instance uaa: uaa/caf3261e-7b24-4fb0-9408-050eb2141c95 (0) (canary) (00:06:22)
	
Task 1238327 | 17:57:16 | Updating instance uaa: uaa/ffbe2634-9b10-474f-9ff4-a43751088432 (1) (00:06:26)
	
Task 1238327 | 18:03:42 | Error: Action Failed get_task: Task ea9c87ed-8617-40c1-78f7-5f2670f205e2 result: 1 of 8 pre-start scripts failed. Failed Jobs: cloud_controller_ng. Successful Jobs: login_banner, bpm, cc_uploader, policy-server, bosh-dns, syslog_forwarder, ca_certs.

### Traces and logs
```
[2019-05-02 17:51:16+0000] /var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/activemodel-5.2.1/lib/active_model/validations/clusivity.rb:8: warning: previous definition of ERROR_MESSAGE was here
[2019-05-02 17:51:17+0000] rake aborted!
[2019-05-02 17:51:17+0000] Sequel::ValidationFailed: Error for shared domain name ns.nd-dev-paas.itn.intraorange: name unique, name overlapping_domain
```

* [ ] I have reviewed provided traces against secrets (credentials, internal URLs) that should not be leake, manually of using some tools such as [truffle-hog file:///user/dxa4481/codeprojects/mytraces.txt](https://github.com/dxa4481/truffleHog#truffle-hog)
 -->

**Comment by poblin-orange** [comment] 2019-05-29 17:11
this issue was due to duplicate between cf manifest and cli /terraform provisonned domains. fixed on terraform automation side

**Closed by poblin-orange** 2019-05-29 17:11 UTC
Labels: bug

**Comment by poblin-orange** [comment] 2019-06-17 00:08
see root cause is #445
